product_list/product_list/urls.py
from django.conf.urls import url, include
# from qpl import views
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^products/', include('qpl.urls')),
]

product_list/qpl/urls.py
from django.conf.urls import url
from qpl import views

app_name = 'qpl'

urlpatterns = [
	url(r'^$', views.BaseView.as_view(), name='base'),
	url(r'^login', views.login_user, name='login'),
	url(r'^register', views.RegisterView.as_view(), name='register'),
	url(r'^register', views.register_user, name='register_user'),
	url(r'^products', views.ProductsView.as_view(), name='products'),
	url(r'^product_added', views.ProductAddedView.as_view(), name='product_added'),

]

product_list/qpl/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=500)
	price = models.CharField(max_length=10)

	def __str__(self):
		return self.name

product_list/product_list/qpl/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django .http import HttpResponse, HttpResponseRedirect

# Create your views here.

# class IndexView(TemplateView):
# 	template_name = 'qpl/'

product_list/qpl/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django .http import HttpResponse, HttpResponseRedirect
from . models import Product


class BaseView(TemplateView):
	template_name = 'base.html'

class LoginView(TemplateView):
	template_name = 'login.html'


class RegisterView(TemplateView):
	template_name = 'register.html'


class ProductsView(View):
	template_name = 'products.html'

	def get(self, request):
		self.products = Product.objects.all()
		return render(request, 'products.html', {'products': self.products})

	def post(self, request):
		data = request.POST
		Product.objects.create(
			name=data['name'],
			description=data['description'],
			price=data['price']
		)
		return HttpResponseRedirect('/products')




class ProductAddedView(TemplateView):
	template_name = 'productAdded.html'

def register_user(request):
	data = request.POST
	User.objects.create_user(
		username=data['username'],
		email=data['email'],
		first_name=data['first_name'],
		last_name=data['last_name'],
		password=data['password']
	)

	return LoginView.login_user(request)

def login_user(request):
    data = request.POST
    username = data['username']
    password = data['password']
    user = authenticate(
    	username=username,
    	password=password
    )

    if user is not None:
    	login(request=request, user=user)
    else:
    	HttpResponseRedirect(redirect_to='/register')
    return HttpResponseRedirect(redirect_to='/products')


def logout_user(request):
	logout(request)
	return HttpResponseRedirect(redirect_to='/')

product_list/qpl/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>QPL</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

product_list/qpl/templates/login.html
{% extends 'base.html' %}

{% block content %}
<form class="" action="{% url 'qpl:login' %}" method="post">
	{% csrf_token %}
	<input type="text" name="username" value="" placeholder="Enter Username">
	<input type="text" name="username" value="" placeholder="Enter Password">
	<button type="submit">Login</button>
</form>
<p>Not a user? Register<a href="{% url 'qpl:register' %}"> here!</a></p>
{% endblock %}

product_list/qpl/templates/products.html
{% extends 'base.html' %}

{% block content %}
<h1>Look! Products</h1>
	{% for product in products %}
		<ul>
			<li style="list-style: none;">{{ forloop.counter }}: {{ product.name }}</li>
		</ul>
	{% endfor %}

<form class="" action="{% url 'qpl:products' %}" method="post">
	{% csrf_token %}
	<input type="text" name="name" value="" placeholder="name">
	<input type="text" name="description" value="" placeholder="description">
	<input type="text" name="price" value="" placeholder="price">
	<button type="submit">ADD PRODUCT</button>
</form>
{% endblock %}

product_list/qpl/templates/register.html
{% extends 'base.html' %}

{% block content %}
<form class="" action="{% url 'qpl:register' %}" method="post">
	{% csrf_token %}
	<input type="text" name="username" value="" placeholder="Username">
	<input type="text" name="email" value="" placeholder="Email">
	<input type="text" name="password" value="" placeholder="Password">
	<input type="text" name="first_name" value="" placeholder="first name">
	<input type="text" name="last_name" value="" placeholder="last name">
	<button type="submit">BUTTON</button>
</form>
{% endblock %}